global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["0.0.0.0:8080"]

  - job_name: "messenger"
    static_configs:
      - targets: ["0.0.0.0:50051"]
