version: "3.9"
services:
  messenger:
    image: tempestmon/messenger:latest
    container_name: messenger
    environment:
      - MESSENGER_HOST=0.0.0.0
      - MESSENGER_PORT=50051
    networks:
      - app_network
    ports:
      - "50051:50051"

  api:
    image: tempestmon/api:latest
    container_name: api
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=50051
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - CORS_URL=https://messenger.tempestmon.ru
    networks:
    - app_network
    ports:
      - "8080:8080"

  frontend:
    image: tempestmon/svelte:latest
    container_name: frontend
    depends_on:
      - api
    networks:
      - app_network
    ports:
      - "8081:80"

networks:
  app_network:
    driver: bridge
