FROM clux/muslrust:1.83.0-stable AS builder

WORKDIR /app

COPY ../api/Cargo.toml /app/
COPY ../api/src /app/src
COPY ../proto /app/proto
COPY ../api/build.rs /app/build.rs

RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch

WORKDIR /app

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/api /usr/local/bin/api

EXPOSE 8080

CMD ["api"]
