FROM nginx:alpine

RUN apk add --no-cache gettext && \
  mkdir -p /etc/nginx/sites-enabled

COPY soryu/site-enabled /etc/nginx/templates
COPY hiryu/public /usr/share/nginx/html/hiryu
COPY soryu/static/tempestmon /var/www/html/tempestmon
COPY soryu/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/letsencrypt

COPY docker/start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh

CMD ["/start-nginx.sh"]
