FROM node:18-alpine AS build

WORKDIR /app

COPY ../svelte-messenger/package*.json /app

RUN npm install

COPY /svelte-messenger /app

# docker-compose api address
ARG API_URL
ENV API_URL=http://api:8080

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/public /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
