version: "3.9"
services:
  messenger:
    image: tempestmon/messenger
    container_name: messenger
    environment:
      - MESSENGER_HOST=0.0.0.0
      - MESSENGER_PORT=50051
    networks:
      - app_network
    ports:
      - "50051:50051"

  api:
    image: tempestmon/api
    container_name: api
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=50051
      - API_HOST=0.0.0.0
      - API_PORT=8080
    networks:
      - app_network
    ports:
      - "8080:8080"

  frontend:
      image: tempestmon/svelte
      container_name: frontend
      depends_on:
        - api
      environment:
        - VITE_API_URL=http://api:8080
      networks:
        - app_network
      ports:
        - "80:80"

networks:
  app_network:
    driver: bridge
