FROM clux/muslrust:1.83.0-stable AS builder

WORKDIR /app

COPY ../messenger/Cargo.toml /app/
COPY ../messenger/src /app/src
COPY ../proto /app/proto
COPY ../messenger/build.rs /app/build.rs

RUN rustup target add x86_64-unknown-linux-musl

RUN cargo build --target x86_64-unknown-linux-musl --release

FROM scratch

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/messenger /usr/local/bin/messenger

EXPOSE 50051

CMD ["messenger"]
