FROM clux/muslrust:1.83.0-stable AS builder

WORKDIR /app

COPY ../akagi/Cargo.toml /app/
COPY ../akagi/src /app/src
COPY ../proto /app/proto
COPY ../akagi/build.rs /app/build.rs

RUN rustup target add x86_64-unknown-linux-musl

RUN cargo build --target x86_64-unknown-linux-musl --release

FROM scratch

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/akagi /usr/local/bin/akagi

EXPOSE 50051

CMD ["akagi"]
