FROM node:18-alpine AS build

WORKDIR /app

COPY ../hiryu/package*.json /app

RUN npm install

COPY /hiryu /app

# docker-compose api address
ARG API_URL
ENV API_URL=https://messenger.tempestmon.ru/api

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/public /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
