FROM clux/muslrust:1.83.0-stable AS builder

WORKDIR /app

COPY ../kaga/Cargo.toml /app/
COPY ../kaga/src /app/src
COPY ../proto /app/proto
COPY ../kaga/build.rs /app/build.rs

RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM scratch

WORKDIR /app

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/kaga /usr/local/bin/kaga

EXPOSE 8080

CMD ["kaga"]
