envoy_listeners:
  - name: http_listener
    port: 80
    domains:
      - "tempestmon.ru"
      - "mail.tempestmon.ru"
      - "messenger.tempestmon.ru"

  - name: https_listener
    port: 443
    tls:
      cert_path: "/etc/letsencrypt/live/tempestmon.ru/fullchain.pem"
      key_path: "/etc/letsencrypt/live/tempestmon.ru/privkey.pem"
    domains:
      - "tempestmon.ru"
      - "mail.tempestmon.ru"
      - "messenger.tempestmon.ru"

envoy_clusters:
  - name: service_web
    address: "127.0.0.1"
    port: 8080
