- name: Deploy Envoy with Validation
  hosts: envoy-server
  become: true
  vars_files:
    - ../vars/main.yml

  tasks:
    # Убедимся, что Docker установлен
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    # Создаём директорию для Envoy, если её нет
    - name: Ensure /etc/envoy directory exists
      ansible.builtin.file:
        path: /etc/envoy
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Загружаем шаблон конфигурации Envoy
    - name: Upload envoy.yml configuration
      ansible.builtin.template:
        src: ../templates/envoy.yml.j2
        dest: /etc/envoy/envoy.yml
        owner: root
        group: root
        mode: '0644'

    # Валидируем конфигурацию
    - name: Validate envoy.yml configuration
      command: >
        docker run --rm
        -v /etc/envoy/envoy.yml:/etc/envoy/envoy.yml:ro
        envoyproxy/envoy:v1.26.0
        --config-path /etc/envoy/envoy.yml
        --mode validate
      register: validate_output
      failed_when: validate_output.rc != 0

    - name: Debug validation output
      ansible.builtin.debug:
        var: validate_output.stdout

    # Создаём директорию для логов
    - name: Ensure /var/log/envoy exists
      ansible.builtin.file:
        path: /var/log/envoy
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Удаляем конфликтующий контейнер, если он есть
    - name: Remove conflicting Envoy container (if exists)
      community.docker.docker_container:
        name: envoy
        state: absent

    # Запускаем Envoy
    - name: Start Envoy container
      community.docker.docker_container:
        name: envoy
        image: envoyproxy/envoy:v1.26.0
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "/etc/envoy/envoy.yml:/etc/envoy/envoy.yml:ro"
          - "/etc/letsencrypt:/etc/letsencrypt:ro"
          - "/var/log/envoy:/var/log/envoy"

    # Проверяем состояние контейнера
    - name: Verify Envoy container is running
      community.docker.docker_container_info:
        name: envoy
      register: envoy_container_info

    - name: Debug Envoy container info
      ansible.builtin.debug:
        var: envoy_container_info
