---
- name: Pull akagi image
  community.docker.docker_image:
    name: tempestmon/akagi
    tag: "{{ akagi_version }}"
    source: pull
    force_source: true

- name: Run akagi container
  community.docker.docker_container:
    name: akagi
    image: "tempestmon/akagi:{{ akagi_version }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "50051:50051"
    env:
      MESSENGER_HOST: "0.0.0.0"
      MESSENGER_PORT: "{{ messenger_port }}"
    comparisons:
      image: strict
      env: strict
