[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.216", features = ["derive"] }
utoipa = "5.2.0"
utoipa-swagger-ui = { version = "8.0.3", features = ["actix-web"] }
