name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Messenger Image
      run: |
        make messenger_build
        docker tag tempestmon/messenger:0.0.1 tempestmon/messenger:latest
        docker push tempestmon/messenger:0.0.1
        docker push tempestmon/messenger:latest

    - name: Build and Push API Image
      run: |
        make api_build
        docker tag tempestmon/api:0.0.1 tempestmon/api:latest
        docker push tempestmon/api:0.0.1
        docker push tempestmon/api:latest

    - name: Build and Push Svelte Image
      run: |
        make svelte_build
        docker tag tempestmon/svelte:0.0.1 tempestmon/svelte:latest
        docker push tempestmon/svelte:0.0.1
        docker push tempestmon/svelte:latest
