name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Messenger Image
      run: |
        make messenger_build
        make messenger_tag
        make messnger_push

    - name: Build and Push API Image
      run: |
        make api_build
        make api_tag
        make api_push

    - name: Build and Push Svelte Image
      run: |
        make svelte_build
        make svelte_tag
        make svelte_push
